### PR TITLE
relax gem dependencies in fedex gem to resolve vulnerability

### PR DESCRIPTION
**Pull request by axlekb**
See [matching commit](https://github.com/jazminschroeder/fedex/commit/a4745a345df2aa76139e9691d4c6d5145e84324f) in the main branch.

### CODE REVIEW

**Comment by axlekb** [comment]
This is to resolve a security vulnerability: http://osvdb.org/show/osvdb/90741

**Comment by mpestritto** [comment]
downgrading to address the security issue? probably fine. not many tests
for this, just need to make sure labels generate.

**Comment by axlekb** [comment]
I wouldn't say it's downgrading, it's more of a relaxing.  With the `~>` it doesn't allow anything more than version `0.9.*`.

**Comment by mpestritto** [comment]
Go for it.

**Comment by axlekb** [comment]
You're in control!  It's your fork!

**Pull request merged**
